test = {   'name': 'q1_1',
    'points': [0, 0, 0, 0],
    'suites': [   {   'cases': [   {'code': '>>> # The first number should be 2004\n>>> int(sc.column("Time").item(0)) == 2004\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # The first five months should be 2004, 2004 + 1/12, 2004 + 2/12 .... 2004 + 4/12\n>>> round(sc.column("Time").item(4), 2) == 2004.33\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> # The 13 month corresponds to January, 2005, so it should be just 2005.\n>>> int(sc.column("Time").item(13)) == 2005\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> sc.labels == ('Month', 'Interest over time', 'Time')\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
