test = {   'name': 'q2_4',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': ">>> # Check your column labels and spelling;\n>>> poverty_map.labels == ('latitude', 'longitude', 'name', 'region', 'poverty_total')\n",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> # Something is wrong with your region column.;\n>>> list(np.sort(np.unique(poverty_map.column('region'))))\n", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
