test = {   'name': 'q3_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': ">>> category(0)\n'low'", 'hidden': False, 'locked': False},
                                   {'code': ">>> category(1)\n'low'", 'hidden': False, 'locked': False},
                                   {'code': ">>> category(2)\n'high'", 'hidden': False, 'locked': False},
                                   {'code': ">>> category(3)\n'high'", 'hidden': False, 'locked': False},
                                   {'code': ">>> category(4)\n'high'", 'hidden': False, 'locked': False},
                                   {'code': ">>> category(5)\n'high'", 'hidden': False, 'locked': False},
                                   {'code': ">>> category(6)\n'high'", 'hidden': False, 'locked': False},
                                   {'code': ">>> category(7)\n'high'", 'hidden': False, 'locked': False},
                                   {   'code': '>>> with_categories.take(np.arange(3))\nstar bakers | won  | category\n3           | 1    | high\n0           | 0    | low\n1           | 0    | low',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
