test = {   'name': 'q2_1',
    'points': [0, 0, 0, 0],
    'suites': [   {   'cases': [   {'code': '>>> prof_names.num_columns\n2', 'hidden': False, 'locked': False},
                                   {'code': '>>> prof_names.num_rows\n71', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # Make sure that you have the correct column labels!\n>>> np.asarray(prof_names.labels).item(1) != "name identity"\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> # Make sure that you have the correct column labels!\n>>> np.asarray(prof_names.labels).item(1) == "faculty"\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
