test = {   'name': 'q8_8',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': ">>> # Please actually go on Piazza and look at the threads.;\n>>> # Looks like you didn't make a string.;\n>>> type(secret) == str\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> len(secret)\n10', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
