test = {   'name': 'q3_2',
    'points': [3, 3],
    'suites': [   {   'cases': [   {   'code': '>>> type(new_left_end) in set([float, np.float32, np.float64]) and type(new_right_end) in set([float, np.float32, np.float64])\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> type(new_sum115_based_estimate) in set([float, np.float32, np.float64, int])\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
